# Import Libraries

In [421]:
import json
import itertools
import pandas as pd
import numpy as np
import random

# Load the datasets

In [422]:
data_df=pd.read_csv('product_and_reviews_dataset.csv')

In [423]:
data_df.head()

,id,asin,title,price,review_count,overall,reviewText,sentimentLabel,score
0,1,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,5,This was the first time I read Garcia-Aguilera...,positive,98
1,2,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,5,"As with all of Ms. Garcia-Aguilera's books, I ...",positive,94
2,3,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,5,I've not read any of Ms Aguilera's works befor...,positive,63
3,4,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,4,This romance novel is right up there with the ...,positive,99
4,5,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,5,Carolina Garcia Aguilera has done it again. S...,positive,75

# Finding overallRating, positive_reviews, negative_reviews, scoreRating

In [424]:
overallRating = data_df.groupby('asin')['overall'].mean()

In [425]:
positive_reviews = data_df[data_df['sentimentLabel'] == 'positive'].groupby('asin').size().rename('positive_count')

In [426]:
negative_reviews = data_df[data_df['sentimentLabel'] == 'negative'].groupby('asin').size().rename('negative_count')

In [427]:
scoreRating = data_df.groupby('asin')['score'].mean()

In [428]:
df = pd.concat([overallRating, positive_reviews, negative_reviews,scoreRating], axis=1).reset_index()

In [429]:
df

            asin   overall  positive_count  negative_count      score
0     045122261X  4.310078           120.0             9.0  79.875969
1     059403390X  4.565217            22.0             1.0  89.739130
2     059448426X  3.201681            83.0            34.0  60.210084
3     059449771X  3.360294            98.0            38.0  59.198529
4     059454582X  4.403061           182.0            14.0  68.295918
...          ...       ...             ...             ...        ...
9931  B0002XN73C  4.716535           125.0             2.0  72.440945
9932  B0002XNSVI  4.640000            73.0             2.0  70.053333
9933  B0002XQI2E  4.651376           108.0             1.0  71.082569
9934  B0002XQJFA  4.679012           158.0             4.0  72.345679
9935  B0002XQKEK  4.642202           106.0             2.0  74.321101

[9936 rows x 5 columns]

In [430]:
df['positive_count'] = result['positive_count'].fillna(0)
df['negative_count'] = result['negative_count'].fillna(0)

In [431]:
df

            asin   overall  positive_count  negative_count      score
0     045122261X  4.310078           108.0            12.0  79.875969
1     059403390X  4.565217             6.0             0.0  89.739130
2     059448426X  3.201681             7.0             0.0  60.210084
3     059449771X  3.360294           108.0            12.0  59.198529
4     059454582X  4.403061            48.0             2.0  68.295918
...          ...       ...             ...             ...        ...
9931  B0002XN73C  4.716535           125.0             2.0  72.440945
9932  B0002XNSVI  4.640000            73.0             2.0  70.053333
9933  B0002XQI2E  4.651376           108.0             1.0  71.082569
9934  B0002XQJFA  4.679012           158.0             4.0  72.345679
9935  B0002XQKEK  4.642202           106.0             2.0  74.321101

[9936 rows x 5 columns]

In [441]:
products_df=data_df

In [442]:
products_df

,id,asin,title,review_count,overall,reviewText,sentimentLabel,score,currency
0,1,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,This was the first time I read Garcia-Aguilera...,positive,98,$
1,2,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,"As with all of Ms. Garcia-Aguilera's books, I ...",positive,94,$
2,3,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,I've not read any of Ms Aguilera's works befor...,positive,63,$
3,4,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,4,This romance novel is right up there with the ...,positive,99,$
4,5,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,Carolina Garcia Aguilera has done it again. S...,positive,75,$
...,...,...,...,...,...,...,...,...,...
998593,998594,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This has an amazing amount of storage and can ...,positive,95,$
998594,998595,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This Item is wonderful I use all the time the ...,positive,95,$
998595,998596,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,My card will not format on my Canon T3i. I've ...,positive,75,$
998596,998597,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,It's getting difficult to find memory cards fo...,positive,89,$
998597,998598,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This works very well in my camera and I love i...,positive,89,$

In [438]:
products_df[['currency', 'price']] = products_df['price'].str.extract(r'(\D*)(\d.*)')

In [400]:
products_df

,asin,title,review_count,currency,Amount
0,0011300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,$,65.00
1,0060009810,One Hot Summer,6,$,11.49
2,0060786817,sex.lies.murder.fame.: A Novel,7,$,13.95
3,0091912407,Girl with a One-track Mind: Confessions of the...,120,$,4.76
4,0132492776,Wireless Bluetooth Headphones Earbuds with Mic...,50,$,7.99
...,...,...,...,...,...
9995,B0002XN73C,reEVOlution iSkin eVot Silicone Case for 40 GB...,127,$,6.04
9996,B0002XNSVI,Hitachi Deskstar 0A30229 400GB SATA/150 7200RP...,75,$,9.99
9997,B0002XQJFA,Canon EOS 20D DSLR Camera with EF-S 18-55mm f/...,162,$,69.35
9998,B0002XQKEK,Opteka 10 Peice Deluxe Lens/Digital Camera Cle...,109,$,4.95
9999,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,$,105.09

In [439]:
products_df.drop('price', axis=1, inplace=True)

In [440]:
products_df

,id,asin,title,review_count,overall,reviewText,sentimentLabel,score,currency
0,1,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,This was the first time I read Garcia-Aguilera...,positive,98,$
1,2,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,"As with all of Ms. Garcia-Aguilera's books, I ...",positive,94,$
2,3,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,I've not read any of Ms Aguilera's works befor...,positive,63,$
3,4,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,4,This romance novel is right up there with the ...,positive,99,$
4,5,11300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,120,5,Carolina Garcia Aguilera has done it again. S...,positive,75,$
...,...,...,...,...,...,...,...,...,...
998593,998594,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This has an amazing amount of storage and can ...,positive,95,$
998594,998595,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This Item is wonderful I use all the time the ...,positive,95,$
998595,998596,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,My card will not format on my Canon T3i. I've ...,positive,75,$
998596,998597,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,It's getting difficult to find memory cards fo...,positive,89,$
998597,998598,B0002XQI2E,Canon EOS 20D DSLR Camera (Body Only) (OLD MODEL),109,5,This works very well in my camera and I love i...,positive,89,$

In [384]:
df['asin']= products_df['asin']
df['title']=products_df['title']
df['price']=products_df['price']
df['review_count']= products_df['review_count']

KeyError: 'price'

In [337]:
df

,asin,overall,positive_count,negative_count,score,title,price,review_count
0,0011300000,4.310078,108.0,12.0,79.875969,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120
1,0060009810,4.565217,6.0,0.0,89.739130,One Hot Summer,$11.49,6
2,0060786817,3.201681,7.0,0.0,60.210084,sex.lies.murder.fame.: A Novel,$13.95,7
3,0091912407,3.360294,108.0,12.0,59.198529,Girl with a One-track Mind: Confessions of the...,$4.76,120
4,0132492776,4.403061,48.0,2.0,68.295918,Wireless Bluetooth Headphones Earbuds with Mic...,$7.99,50
...,...,...,...,...,...,...,...,...
9931,B0002VFXGI,4.716535,125.0,2.0,72.440945,Mad Dog Multimedia PC Slot Cooler (MD-PC-SF) (...,$12.96,101
9932,B0002VFXGS,4.640000,73.0,2.0,70.053333,Mad Dog Multimedia DiskMod Hard Disk Drive Dua...,$1.54,193
9933,B0002VK9BW,4.651376,108.0,1.0,71.082569,Sony INT-W250 WebTv Internet Terminal,$36.49,187
9934,B0002VMV2M,4.679012,158.0,4.0,72.345679,BOSS Audio AVA6200 Enclosed Speaker System - 3...,$4.00,188
9935,B0002VMVMW,4.642202,106.0,2.0,74.321101,BOSS Audio AVA1210 Car Equalizer - 7 Band Pre-...,$6.04,23

# Rearranging the columns

In [338]:
df = df.reindex(columns=['asin', 'title', 'price', 'review_count', 'overall', 'positive_count', 'negative_count', 'score'])

In [339]:
df

,asin,title,price,review_count,overall,positive_count,negative_count,score
0,0011300000,Genuine Geovision 1 Channel 3rd Party NVR IP S...,$65.00,120,4.310078,108.0,12.0,79.875969
1,0060009810,One Hot Summer,$11.49,6,4.565217,6.0,0.0,89.739130
2,0060786817,sex.lies.murder.fame.: A Novel,$13.95,7,3.201681,7.0,0.0,60.210084
3,0091912407,Girl with a One-track Mind: Confessions of the...,$4.76,120,3.360294,108.0,12.0,59.198529
4,0132492776,Wireless Bluetooth Headphones Earbuds with Mic...,$7.99,50,4.403061,48.0,2.0,68.295918
...,...,...,...,...,...,...,...,...
9931,B0002VFXGI,Mad Dog Multimedia PC Slot Cooler (MD-PC-SF) (...,$12.96,101,4.716535,125.0,2.0,72.440945
9932,B0002VFXGS,Mad Dog Multimedia DiskMod Hard Disk Drive Dua...,$1.54,193,4.640000,73.0,2.0,70.053333
9933,B0002VK9BW,Sony INT-W250 WebTv Internet Terminal,$36.49,187,4.651376,108.0,1.0,71.082569
9934,B0002VMV2M,BOSS Audio AVA6200 Enclosed Speaker System - 3...,$4.00,188,4.679012,158.0,4.0,72.345679
9935,B0002VMVMW,BOSS Audio AVA1210 Car Equalizer - 7 Band Pre-...,$6.04,23,4.642202,106.0,2.0,74.321101

# Save the new dataset to a file or database

In [340]:
df.to_csv('trustworth_score_finding_dataset.csv', index=False)